version: '3.0'
services:
  app:
    build: 
        context : .
        dockerfile : docker/Dockerfile
    container_name: phone-number-auth
    image : phone-number-auth 
    restart: always
    ports:
      - "3000:3000"
  
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DATABASE=${POSTGRES_USERNAME}
      - POSTGRES_USERNAME=${POSTGRES_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_DATABASE}
    ports:
      - '5432:5432'
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer : 
    image:  adminer:latest
    restart: always 
    ports:
      - '4000:8080'
    
